# Generated by Django 5.1 on 2024-11-04 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('time_period', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WrapTrack',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('listen_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='WrapAlbum',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('listen_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.wrap')),
            ],
        ),
        migrations.CreateModel(
            name='WrapUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.BooleanField()),
                ('accepted', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.user')),
                ('wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.wrap')),
            ],
        ),
    ]
