# Generated by Django 5.1 on 2024-11-04 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0004_post_like_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='wraptrack',
            name='wrap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.wrap'),
            preserve_default=False,
        ),
    ]
