# Generated by Django 5.1 on 2024-11-04 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0006_remove_wraptrack_wrap_delete_wrapartist_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrapArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=255)),
                ('listen_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.wrap')),
            ],
        ),
        migrations.CreateModel(
            name='WrapTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.CharField(max_length=255)),
                ('listen_time', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('wrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wrapped.wrap')),
            ],
        ),
    ]
