# Generated by Django 5.1 on 2024-11-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrapped', '0010_wrapartist_user_wraptrack_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wrap',
            name='artist_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wrap',
            name='track_count',
            field=models.IntegerField(default=0),
        ),
    ]
