name: Python + TypeScript Linter

on:
  pull_request:
    branches:
      - main

jobs:
  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt
          pip install flake8
      - name: Lint with flake8
        run: |
          flake8 backend/
  ts-lint:
    name: TypeScript Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "21"
      - name: Install dependencies
        run: |
          npm install -g pnpm
          cd frontend && pnpm install
      - name: Lint with ESLint
        run: |
          cd frontend && pnpm run lint
